TARGET	= libmatmult.so
LIBSRCS	= source_gcc.c 
LIBOBJS	= $(LIBSRCS:.c=.o)

OPT	= -g -L/usr/lib64/atlas -lsatlas
PIC	= -fPIC

CC	= gcc
CFLAGS= $(OPT) $(PIC) $(XOPTS)

SOFLAGS = -shared 
XLIBS	= 

$(TARGET): $(LIBOBJS)
	$(CC) -o $@ $(SOFLAGS) $(LIBOBJS) $(XLIBS)

clean:
	@/bin/rm -f core core.* $(LIBOBJS) 
